Feat 960 1 ampliutude to airflow
cal-itp/data-infra pull request #1121
Opened 2022-02-24 00:23 UTC by machikoyasuda

## Description

Related to #960, closes #1046 

This PR merges this branch into the feature branch, `feat-amplitude-operator`. @angela-tran and @machikoyasuda paired on it.

This PR adds to the `amplitude_to_df` function some logic to call the Amplitude Export API and read the returned zipped stream into a Pandas DataFrame. 

## What this PR does and does not do
- See the first commit [`98403dd`](https://github.com/cal-itp/data-infra/pull/1081/commits/98403ddfb5f402225407f9753651b5c67f8c933a) for the basic implementation
- This PR does not add error handling.
- This PR does not attempt to transform the raw data into any specific schema.
- This PR does not have Pytests. (We could write proper pytests which I think would be done as a separate issue.)

## Pre-requisites for testing locally

1. Change `.devcontainer/Dockerfile` line 4:
```diff
-ARG VARIANT="3.9"
+ARG VARIANT="3.8"
```
2. Export `CALITP_AMPLITUDE_BENEFITS_API_KEY` and `CALITP_AMPLITUDE_BENEFITS_SECRET_KEY` key value pairs. Get key/secret from Amplitude.

## How to test

I tested these changes myself by writing some simple, throwaway code to call the function with various start/end dates and keys I got from Amplitude. 

1. Modify `airflow/debug.py`
```diff
-import os
-import sys
+# import os
+# import sys
 
-import dotenv
+# import dotenv
 
-dotenv.load_dotenv()
+# dotenv.load_dotenv()
 
-sys.path.append(os.path.abspath("plugins"))
+# sys.path.append(os.path.abspath("plugins"))
+
+import plugins.operators.amplitude_to_warehouse as atw
+
+df = atw.amplitude_to_df("20220101T05", "20220102T05")
+print(df)
```
2. Run `python -m debug.py` and expect data to be returned:
```bash
       app                             device_id  ... $schema             processed_time
0   304110  2842c0b8-a104-847e-63b7-dab84adb1196  ...      13 2022-01-01 05:07:43.196789
1   304110  9bc14448-275d-9755-9425-61aed7b38605  ...      13 2022-01-01 05:03:55.122934
2   304110  cb836441-943a-a9a4-baaf-8f28e9603d62  ...      13 2022-01-01 05:08:51.600550
3   304110  92d55c52-da91-ab9f-957e-1bf327d915e1  ...      13 2022-01-01 05:10:04.664107
```

## Checklist for all PRs

- [x] Run `pre-commit run --all-files` to make sure markdown/lint passes
- [x] Link this pull request to all issues that it will close using keywords (see GitHub docs about [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). Also mention any issues that are partially addressed or are related.

2022-02-24 17:23 UTC, atvaccaro commented
Based on our conversation last week, is there a compelling reason to use a custom Operator and/or pandas here? I feel like a generic PythonOperator will work, with a function that simply downloads Amplitude zipped files and then uploads to GCS?

2022-02-24 17:40 UTC, thekaveman commented
> Based on our conversation last week, is there a compelling reason to use a custom Operator and/or pandas here? I feel like a generic PythonOperator will work, with a function that simply downloads Amplitude zipped files and then uploads to GCS?

Thanks for this feedback @atvaccaro! I think we were modeling this based on the [`RealtimeToFlattenedJSONOperator`](https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/operators/realtime_to_flattened_json_operator.py). Can you point us to an example of using a generic `PythonOperator`? The use of an intermediate dataframe was mostly a convenience for appending multiple JSON files together. 

Note too that this code is only one half, the Amplitude API consumption, which is done in normal Python function outside of the custom operator. If this pattern makes sense / works with a `PythonOperator` I think we'd be happy to use that instead of a custom operator. 

And finally, as we discussed we are anticipating additional use-cases in Amplitude for other Cal-ITP projects. Does that impact our decision to use a `PythonOperator` or create a custom operator as we've (started to do) here?

2022-02-24 17:45 UTC, thekaveman requested changes

2022-02-24 17:45 UTC, thekaveman commented on airflow/plugins/operators/amplitude_to_flattened_json.py
> +    secret_key: str = os.environ.get("CALITP_AMPLITUDE_BENEFITS_SECRET_KEY"),
It seems a little awkward / unnecessary to have the default values do the environment lookup?

I think it's more natural for the defaults be `None` and do the lookup inside the function body only if needed.

2022-02-24 18:12 UTC, atvaccaro commented
Yeah a generic PythonOperator (see any `.py` file with https://github.com/cal-itp/data-infra/blob/main/airflow/dags/rt_loader/create_validation_params.py as a good example, since gusty picks up those as PythonOperators) could work fine here (for the one-off), you can still import functions, etc. Gusty really helps to reduce the gap between a PythonOperator and a custom operator; there really wouldn't be too much of a difference between a PythonOperator whose arguments are the configuration, vs a custom operator where the yaml is the configuration (and the yaml just becomes Python kwargs anyways).

I had definitely forgotten about plans for future integrations. I think a dedicated operator makes sense; I would probably scope it to download an Amplitude zip and uploading to GCS. Then, use SQL to create the external bigquery tables (gusty picks up any `.sql` file as a SQLOperator).

2022-02-24 18:14 UTC, thekaveman commented
> I think a dedicated operator makes sense; I would probably scope it to download an Amplitude zip and uploading to GCS.

That is definitely the scope we had in mind! The name `AmplitudeToWarehouse` is probably a misnomer from our previous plan/scope, so we can rename to `AmplitudeToFlattenedJSON` or similar. 

Thanks for your continued assistance here!

2022-02-24 18:17 UTC, thekaveman requested changes

2022-02-24 18:17 UTC, thekaveman commented on airflow/plugins/operators/amplitude_to_flattened_json.py
> +class AmplitudeToWarehouseOperator(BaseOperator):
Since this PR renames the file (and based on our new plan), let's also rename the operator class. Something like `AmplitudeToFlattenedJSONOperator`.

2022-02-24 20:32 UTC, machikoyasuda commented
@thekaveman https://github.com/cal-itp/data-infra/pull/1121/ is ready for re-review.

Changes:
1. Rename the class
2. Move API key and secret lookup
3. Add more detailed docstrings

2022-02-25 00:42 UTC, thekaveman approved these changes
This is great! I was able to run it locally and get output from the DataFrame! 

🚢 on to GCS! 📂

2022-02-25 02:56 UTC, atvaccaro approved these changes
lgtm!

2022-02-28 20:07 UTC, merged