only tick when seconds are evenly divisible by 20
cal-itp/data-infra pull request #1147
Opened 2022-02-28 20:40 UTC by chriscauley

# Overall Description

Currently the loop is `while True: sleep(20); tick()`. But since `tick()` isn't infinitely fast the actual delay is slightly larger than 20 seconds. This just says "sleep however much time until time.time() is a multiple of 20". This will stop the drift and make it so every timestamp is a multiple of 20.

## Checklist for all PRs

- [x] Run `pre-commit run --all-files` to make sure markdown/lint passes
- [ ] Link this pull request to all issues that it will close using keywords (see GitHub docs about [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). Also mention any issues that are partially addressed or are related.

2022-02-28 20:53 UTC, lottspot approved these changes
Clever!

2022-02-28 20:57 UTC, lottspot requested changes
Actually-- is this working as expected?

2022-02-28 21:00 UTC, lottspot approved these changes
Silly me, I did not replicate the algo correctly. Looks good!

```python
>>> for n in range(10): time.sleep(1); 20 - (time.time() % 20)
... 
17.16589856147766
16.164714336395264
15.164386749267578
14.163253545761108
13.16213607788086
12.161062240600586
11.159938335418701
10.158769369125366
9.157790184020996
8.156683206558228
```

2022-02-28 23:12 UTC, evansiroky approved these changes
Nice!

2022-03-02 00:30 UTC, chriscauley commented
@lottspot It's not `sleep(time % 20)` it's `sleep(20 - time % 20)`. So if unix time is 1646172919 it will sleep 1 second (because `20 - xxx19 === 1`.

``` python
import time, random


TICKINT = 20
print("Start time:", time.time())
for n in range(10):
    time.sleep(TICKINT - time.time()%TICKINT) #will sleep until unix time is a multiple of tickint                                                                                                                 
    print("Current time should be a multiple of 20:", time.time())

    delay = random.randint(0,19)
    print("Random delay is ", delay)
    time.sleep(delay)
```

Outputs:

```
Start time: 1646173777.421639
Current time should be a multiple of 20: 1646173780.002695
Random delay is  3
Current time should be a multiple of 20: 1646173800.0040193
Random delay is  16
Current time should be a multiple of 20: 1646173820.0040858
Random delay is  2
Current time should be a multiple of 20: 1646173840.018112
Random delay is  13
Current time should be a multiple of 20: 1646173860.0070662
Random delay is  12
Current time should be a multiple of 20: 1646173880.0080945
Random delay is  8
Current time should be a multiple of 20: 1646173900.012097
Random delay is  4
Current time should be a multiple of 20: 1646173920.0160987
Random delay is  11
Current time should be a multiple of 20: 1646173940.0090683
Random delay is  12
Current time should be a multiple of 20: 1646173960.0080857
Random delay is  15
```

If the loop takes 0.01 s between cycles, time.sleep will only sleep for 19.9s instead of 20. This means all the timestamps will be 20s apart and end with 20 (or a multiple of TICKINT).

2022-03-14 14:36 UTC, lottspot commented
> @lottspot It's not `sleep(time % 20)` it's `sleep(20 - time % 20)`. So if unix time is 1646172919 it will sleep 1 second (because `20 - xxx19 === 1`.
> 
> ```python
> import time, random
> 
> 
> TICKINT = 20
> print("Start time:", time.time())
> for n in range(10):
>     time.sleep(TICKINT - time.time()%TICKINT) #will sleep until unix time is a multiple of tickint                                                                                                                 
>     print("Current time should be a multiple of 20:", time.time())
> 
>     delay = random.randint(0,19)
>     print("Random delay is ", delay)
>     time.sleep(delay)
> ```
> 
> Outputs:
> 
> ```
> Start time: 1646173777.421639
> Current time should be a multiple of 20: 1646173780.002695
> Random delay is  3
> Current time should be a multiple of 20: 1646173800.0040193
> Random delay is  16
> Current time should be a multiple of 20: 1646173820.0040858
> Random delay is  2
> Current time should be a multiple of 20: 1646173840.018112
> Random delay is  13
> Current time should be a multiple of 20: 1646173860.0070662
> Random delay is  12
> Current time should be a multiple of 20: 1646173880.0080945
> Random delay is  8
> Current time should be a multiple of 20: 1646173900.012097
> Random delay is  4
> Current time should be a multiple of 20: 1646173920.0160987
> Random delay is  11
> Current time should be a multiple of 20: 1646173940.0090683
> Random delay is  12
> Current time should be a multiple of 20: 1646173960.0080857
> Random delay is  15
> ```
> 
> If the loop takes 0.01 s between cycles, time.sleep will only sleep for 19.9s instead of 20. This means all the timestamps will be 20s apart and end with 20 (or a multiple of TICKINT).

I realized this in [my follow up reply](https://github.com/cal-itp/data-infra/pull/1147#pullrequestreview-895588801) :slightly_smiling_face:

2022-03-14 14:36 UTC, merged