Moved payments dashboard queries from metabase into the warehouse
cal-itp/data-infra pull request #1876
Opened 2022-10-04 23:23 UTC by charlie-costanzo

# Description

Moving the visualizations on the payments dashboard that are written directly into Metabase to the warehouse

Resolves #1175 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] agencies.yml

## How has this been tested?

## Screenshots (optional)

2022-10-13 18:22 UTC, mjumbewu commented on warehouse/models/payments_views_staging/stg_cleaned_device_transactions.sql
> +    ST_GEOGPOINT(CAST(longitude AS FLOAT64), CAST(latitude AS FLOAT64)) AS geography
:heart_eyes:

2022-10-13 18:40 UTC, mjumbewu requested changes
Just a couple suggestions. Otherwise, love it!

2022-10-13 18:40 UTC, mjumbewu commented on warehouse/models/payments_views_staging/stg_cleaned_device_transactions.sql
> +    ST_GEOGPOINT(CAST(longitude AS FLOAT64), CAST(latitude AS FLOAT64)) AS geography
**suggestion:** If you cast the lng/lat above, you won't need to here.

```suggestion
    ST_GEOGPOINT(longitude, latitude) AS geography
```

2022-10-25 18:38 UTC, charlie-costanzo commented
> Just a couple suggestions. Otherwise, love it!

Hey thank you so much for the feedback Mjumbe! I just committed your suggestions, ran them locally, and re-requested review

2022-11-15 16:31 UTC, charlie-costanzo commented
Heyo! Wondering what you two think about merging this now that the review requests above have been taken care of @mjumbewu @j-meelah

2022-11-22 16:11 UTC, atvaccaro approved these changes
can you run sqlfluff on this locally since it's disabled in CI/CD?

2022-11-22 16:48 UTC, atvaccaro commented on warehouse/models/payments_views/payments_rides.sql
> +    ST_DISTANCE(on_geography, off_geography) / 1609.34 AS distance
Oops good catch

2022-11-22 16:51 UTC, charlie-costanzo commented on warehouse/models/payments_views/payments_rides.sql
> +    ST_DISTANCE(on_geography, off_geography) / 1609.34 AS distance
cool cool, gonna remove the miles calculation and rename to `distance_meters`

2022-11-29 17:20 UTC, merged