Availability of Google Cloud data access logs in mart
cal-itp/data-infra pull request #2116
Opened 2023-01-03 22:10 UTC by SorenSpicknall

# Description

In order to facilitate more detailed dashboarding for infra costs, this PR seeks to republish the entirety of `stg_audit__cloudaudit_googleapis_com_data_access` in mart, where it'll be usable by Metabase.

This contributes to, but does not yet fully resolve, #2022.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] agencies.yml

## How has this been tested?

At the time of writing, table creation has been tested in the staging project via locally issued dbt commands. Work remains to be done before it's ready for production.

## Screenshots (optional)

2023-01-06 20:26 UTC, atvaccaro requested changes

2023-01-06 20:26 UTC, atvaccaro commented on warehouse/models/mart/audit/fct_bigquery_data_access.sql
> +        referenced_tables,
can you either unnested in this model or create another table on top that unnests? I think seeing a rough breakdown of data volumes by queried table (i.e. read not write) may be useful; a table that is expensive to build but efficient to query is probably preferable for most of our uses cases.

2023-01-09 17:03 UTC, atvaccaro requested changes
I think even the unnested model seems like a fact? maybe `fct_bigquery_referenced_tables` and then you could add a caveat in the documentation about how it will overcount

2023-01-09 18:15 UTC, SorenSpicknall commented
> I think even the unnested model seems like a fact? maybe `fct_bigquery_referenced_tables` and then you could add a caveat in the documentation about how it will overcount

Totally right there - I gave it that name before actually deciding how to structure the table. I'll make that change in the next commit.

2023-01-09 19:24 UTC, atvaccaro approved these changes
lgtm!

2023-01-09 19:32 UTC, merged