add line number to schedule jsonl files
cal-itp/data-infra pull request #2121
Opened 2023-01-04 16:50 UTC by atvaccaro

# Description

The schedule backfill has caused many dbt tests to start failing, for example [fare rules having duplicate rows](https://sentry.calitp.org/organizations/sentry/issues/4509/?environment=cal-itp-data-infra&project=2&query=is%3Aunresolved+dbt&statsPeriod=14d). We don't really want to filter these out immediately, but we do want to ensure that we're ending up with 1 record per row in the original extract file. Adding a line number to the CSV-to-JSONL conversion task will let us check for a unique combination of ts, url, and line number.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] agencies.yml

## How has this been tested?

## Screenshots (optional)

2023-01-10 14:49 UTC, lauriemerrell requested changes
Can you add this to the external tables in this PR too? 

How long do you think it will take / cost to backfill this through all of history? I am still not very sold on backfill, I am wondering if we can add tests just from when this is added forward. If there is structural fanout that should still catch it.

2023-01-10 17:08 UTC, atvaccaro commented
> How long do you think it will take / cost to backfill this through all of history? I am still not very sold on backfill, I am wondering if we can add tests just from when this is added forward. If there is structural fanout that should still catch it.

I don't think it'll be too bad; the worst are stop_times (~30 min/day) and shapes (~10 min/day) and we don't have to re-run validate or unzip tasks. (stats from https://o1d2fa0877cf3fb10p-tp.appspot.com/duration?dag_id=unzip_and_validate_gtfs_schedule&days=30)

2023-01-13 15:40 UTC, atvaccaro commented
I think we can merge this and just selectively backfill when we want, from the day of merge. (Trying to close out PRs)

2023-01-17 16:02 UTC, lauriemerrell approved these changes

2023-01-17 16:21 UTC, merged