add gtfs aggregator checks
cal-itp/data-infra pull request #2177
Opened 2023-01-17 21:56 UTC by owades

# Description

Use the new aggregator scraper to check for each feed's presence on transit.land and mobility database.

One part of this that I'd like feedback on is the way that I ignore HTTP vs HTTPS (removing everything before "://" in the URL). Specifically I see that some aggregators have URLs listed starting with "ftp://" and I'm not sure whether these should be included or omitted.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] agencies.yml

## How has this been tested?
Manually reviewed multiple passing and failing values. As an example of a failing value, I found that the URL we have listed for Desert Roadrunner is `https://data.trilliumtransit.com/gtfs/paloverde_valley-ca-us/paloverde_valley-ca-us.zip`, while the URL listed on transit.land is `http://data.trilliumtransit.com/gtfs/paloverde-valley-ca-us/paloverde-valley-ca-us.zip` (note the underscore/hyphen discrepancy between "paloverde" and "valley" - this is what the check is for!)

Also ran dbt build on both tables and confirmed no errors, and no new downstream errors

2023-01-17 22:56 UTC, atvaccaro requested changes
One broad comment: I _might_ recommend only doing the URL protocol handling in the joins, and maybe dig more into the ftp records? IMO I think that if we have HTTP(S) and the aggregator has FTP that's probably something we want to flag? Can discuss more in Slack/Zoom if you'd like.

2023-01-17 22:56 UTC, atvaccaro commented on warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__schedule_feed_guideline_index_aggregator.sql
> +),
nit: I think you could pull the minimum date from stg_gtfs_quality__scraped_urls and use that to filter the index

2023-01-17 22:56 UTC, atvaccaro commented on warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__feed_aggregator_rt.sql
> +),
nit: this feels a bit fragile, regex may be a bit more explicit?

2023-01-17 22:56 UTC, atvaccaro commented on warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__feed_aggregator_rt.sql
> +        END AS status,
nit: you could nest the `case` statements to reduce repetition

2023-01-17 22:56 UTC, atvaccaro commented on warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__feed_aggregator_schedule.sql
> +    FROM {{ ref('dim_gtfs_datasets') }}
I'd recommend using a macro if this is being done in multiple places

2023-01-18 00:06 UTC, owades commented
> One broad comment: I _might_ recommend only doing the URL protocol handling in the joins, and maybe dig more into the ftp records? IMO I think that if we have HTTP(S) and the aggregator has FTP that's probably something we want to flag? Can discuss more in Slack/Zoom if you'd like.

Ok, a bit more info about the ftp thing. There are only 7 URLs listed (if they are even technically URLs) starting with "ftp://". They're all from transitland, and only 2 appear to be in the US.

For at least [this one](https://www.transit.land/feeds/f-9qbdx-santarosacitybus), it's listed as the url from "historic GTFS". Either way, I feel good about filtering these out. Going to do so now.

```
ftp.scgov.net/pub/scat/SCATGTFS.zip
ftp.ci.santa-rosa.ca.us/SantaRosaCityBus/google_transit.zip
gtfs.mot.gov.il/israel-public-transportation.zip
ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/ATTG/dbus/google_transit.zip
ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/MetroBilbao/google_transit.zip
ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/Euskotren/google_transit.zip
ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/FunicularArtxanda/google_transit.zip
```

2023-01-18 00:34 UTC, owades commented
@atvaccaro thanks for pushing me to write higher quality stuff. I've made all of the relevant updates. I'm also no longer filtering out the ftp addresses, as the regex logic in the join does it automatically (by requiring text to contain "http"

2023-01-18 16:15 UTC, atvaccaro approved these changes
lgtm!

2023-01-18 16:15 UTC, merged