Allow RT Validation to Use Most Recent Available Schedule Feeds (Up to 7 Days)
cal-itp/data-infra pull request #2400
Opened 2023-03-17 16:48 UTC by SorenSpicknall

# Description

We currently have a gap in RT validation caused by missing schedule extracts during times of day before the current day's schedule extracts have been processed. This PR allows RT validation to look back on the previously extracted version of the schedule, with a delay of up to seven days, before failing.

Resolves #2306

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] agencies.yml

## How has this been tested?

Various pieces of the changed code have been tested locally, but at the time of PR creation the whole GTFS RT Parser job has not yet been run in local Airflow.

2023-03-17 17:03 UTC, atvaccaro requested changes

2023-03-17 22:02 UTC, SorenSpicknall commented on jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
> +        )
Resolved in [b8f81e7](https://github.com/cal-itp/data-infra/pull/2400/commits/b8f81e79e8396547ff9cde872b6fcd606245fc9d)

2023-03-20 16:53 UTC, SorenSpicknall commented on jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
> +            ]
Resolved in [e17298d](https://github.com/cal-itp/data-infra/pull/2400/commits/e17298d73e45b88f7008f457e7c84ea34a5ecaac)

2023-03-20 18:27 UTC, atvaccaro approved these changes
lgtm!

2023-03-20 18:27 UTC, atvaccaro commented on jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
> +    today = first_extract.dt
nit: maybe `extract_day` or something

2023-03-20 21:32 UTC, merged