Jupyter dep updates
cal-itp/data-infra pull request #2418
Opened 2023-03-23 21:12 UTC by atvaccaro

# Description

Describe your changes and why you're making them. Please include the context, motivation, and relevant dependencies.

Resolves # [issue]

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] agencies.yml

## How has this been tested?

## Screenshots (optional)

2023-03-23 22:23 UTC, tiffanychu90 commented
@atvaccaro: Did you mean to remove the `requirements.txt`? Looking for [these](https://github.com/cal-itp/data-analyses/blob/remove-shared-utils-pkgs/_shared_utils/requirements.txt) also to be in the poetry file

2023-03-23 22:24 UTC, tiffanychu90 requested changes
@atvaccaro: Did you mean to remove the requirements.txt? Looking for [these](https://github.com/cal-itp/data-analyses/blob/remove-shared-utils-pkgs/_shared_utils/requirements.txt) also to be in the poetry file

2023-03-23 23:23 UTC, atvaccaro commented
> @atvaccaro: Did you mean to remove the requirements.txt? Looking for [these](https://github.com/cal-itp/data-analyses/blob/remove-shared-utils-pkgs/_shared_utils/requirements.txt) also to be in the poetry file

Ah yes I meant to remove the file but good catch; will add the shared_utils requirements now that we're not installing the library itself anymore.

2023-03-24 18:14 UTC, tiffanychu90 approved these changes

2023-03-24 18:58 UTC, merged