Analyst POC tables from Issues #2381 and #2382
cal-itp/data-infra pull request #2426
Opened 2023-03-27 15:18 UTC by charlie-costanzo

# Description
Analyst POC tables as requested in #2381 and #2382
* `fct_observed_trips_summaries`
* `fct_daily_scheduled_shapes_monthly_aggregations`

Resolves #2381 and #2382

## Type of change

- [x] New feature

## How has this been tested?
local `dbt run` and `dbt test`

2023-03-27 17:11 UTC, charlie-costanzo commented on warehouse/models/mart/ad_hoc/fct_observed_trips_summaries.sql
To-do:
* These should be added columns to `fct_observed_trips`
* Select only one week of data
* Make a fake incremental - this is large data and we don't want it run every day

2023-03-27 17:21 UTC, charlie-costanzo commented on warehouse/models/mart/ad_hoc/fct_observed_trips_summaries.sql
Questions:
* What do you want the number of distinct minutes to be
* Put it on fct_observed_trips - derive daypart - if there is a trip_start_time use that, if not, then use min_extract_ts
  * The, when we join schedule and RT in a more combined model, then we can have some logic to reconcile if the two have a different time of day for the same trip

2023-03-27 17:27 UTC, charlie-costanzo commented on warehouse/models/mart/ad_hoc/fct_daily_scheduled_shapes_monthly_aggregations.sql
Actual question:
* For every month, for every route, what is the most common shape
* "`fct_monthly_common_shape_by_route`"

2023-03-31 20:21 UTC, lauriemerrell requested changes
Overall looks good, I think `INTERVAL` is actually super clutch and we need to figure out how to use it more broadly for this, but I just have some suggested tweaks -- happy to discuss on a short call on Monday if you want

2023-04-03 14:03 UTC, charlie-costanzo commented on warehouse/models/mart/ad_hoc/fct_observed_trips_summaries.sql
> +        -- Cast to interval because it's a string, with <24hr values, so cast to time breaks
yeah my bad this is a typo

2024-01-18 18:47 UTC, mjumbewu commented
The issues that spurred this PR have since been closed with other solutions. This PR doesn't seem necessary anymore, so closing (/cc @tiffanychu90).

2024-01-18 18:47 UTC, closed without merging