Adjust trip updates materializations
cal-itp/data-infra pull request #2458
Opened 2023-04-05 17:54 UTC by atvaccaro

# Description

Resolves https://github.com/cal-itp/data-infra/issues/2401 once backfill runs

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] agencies.yml

## How has this been tested?
Testing locally.

## Screenshots (optional)

2023-04-05 20:30 UTC, lauriemerrell requested changes
Mostly looks good, just a few questions.

2023-04-05 20:30 UTC, lauriemerrell commented on warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
> +      Incrementally trip update messages without stop times; this reduces the data size by about 90%.
`incrementally` wordo / missing word?

2023-04-05 20:30 UTC, lauriemerrell commented on warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
> +  - name: fct_service_alerts_trip_summaries
Can we add some documentation about the columns / what exactly is being summarized in this and the other two?

2023-04-05 20:30 UTC, lauriemerrell commented on warehouse/models/mart/gtfs/fct_trip_updates_summaries.sql
I guess if you do a copy operation we don't have to do a full backfill, but should we take this opportunity to add a COUNT DISTINCT header/vehicle/trip timestamp, given that we have discovered that message ID should generally persist throughout a given trip / vehicle on a given day (so count distinct message ID is not actually a count of messages in which the trip appeared)?

2023-04-05 21:31 UTC, atvaccaro commented on warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
> +      Incrementally trip update messages without stop times; this reduces the data size by about 90%.
yes

2023-04-06 15:01 UTC, lauriemerrell reviewed
Sorry just a few more docs requests. My experience with the datetime stuff is making me think that we need to more explicitly document the different types of timestamps and not just rely on naming conventions

2023-04-06 15:01 UTC, lauriemerrell commented on warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
> +      - *num_distinct_header_timestamps
can you add `num_distinct_trip_timestamps`

2023-04-06 15:01 UTC, lauriemerrell commented on warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
> +      - *num_distinct_header_timestamps
can you add `num_vehicle_timestamps`

2023-04-06 15:51 UTC, atvaccaro commented
> Sorry just a few more docs requests. My experience with the datetime stuff is making me think that we need to more explicitly document the different types of timestamps and not just rely on naming conventions

yep good catches, thank you

2023-04-06 16:30 UTC, lauriemerrell approved these changes

2023-04-10 16:37 UTC, merged

2023-04-10 16:42 UTC, atvaccaro commented
I've executed the following.

```sql
CREATE TABLE mart_gtfs.fct_trip_updates_no_stop_times
    COPY staging.int_gtfs_rt__trip_updates_no_stop_times;

CREATE TABLE mart_gtfs.fct_trip_updates_summaries
    COPY staging.int_gtfs_rt__trip_updates_summaries;

CREATE TABLE mart_gtfs.fct_vehicle_positions_trip_summaries
    COPY staging.int_gtfs_rt__vehicle_positions_trip_summaries;

```