Update `fct_scheduled_service_by_daypart`
cal-itp/data-infra pull request #2738
Opened 2023-06-20 19:59 UTC by tiffanychu90

# Description
_Describe your changes and why you're making them. Please include the context, motivation, and relevant dependencies._

Remove `shape_id` from `fct_scheduled_service_by_daypart` and include the sum of `service_hours` as `ttl_service_hours` from aggregation.

Resolves #2234 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## How has this been tested?
_Include commands/logs/screenshots as relevant._

## Post-merge follow-ups
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and link it here to track resolution._

- [ ] No action required
- [ ] Actions required (specified below)

2023-06-20 21:06 UTC, lauriemerrell requested changes
Changes to service by daypart are all good! But I think the changes to `fct_observed_trips` here would be more appropriate as a separate model, see inline comment. Also happy to have a short meeting to discuss if that would help. (There's a bunch of in-flight work on #2489 that is relevant here; I didn't realize that you'd be working on this, so would love to coordinate.)

2023-06-20 21:06 UTC, lauriemerrell commented on warehouse/models/mart/gtfs/fct_observed_trips.sql
> +    FULL OUTER JOIN scheduled_trips
Adding a full outer join to `scheduled trips` here is a pretty major change to the overall warehouse DAG (by adding a schedule trips dependency here) and actually changes the grain of `fct_observed_trips` from only RT trips to both scheduled & RT trips. 

I think it would be preferable to make a separate, second table that compares schedule & RT, if that is ok? There's a ticket for this, currently assigned to me: https://github.com/cal-itp/data-infra/issues/2685 -- if you'd like to tackle that in a new separate PR, that would be great! Note also that I am planning changes to `fct_observed_trips` in #2489, to make a better `service_date` analog in that table. (Right now `dt` in `fct_observed_trips` is a UTC date and therefore not directly comparable with `service_date`; see #2347).

Also note to self that any changes to `fct_observed_trips` would probably warrant changes to the two GTFS guideline check models that reference it: https://dbt-docs.calitp.org/#!/model/model.calitp_warehouse.fct_observed_trips#referenced_by.

2023-06-20 21:55 UTC, tiffanychu90 commented on warehouse/models/mart/gtfs/fct_observed_trips.sql
> +    FULL OUTER JOIN scheduled_trips
Ahh ok, I actually didn't realize the grain would change, I think I wanted just the `service_hours` column added, but it does make sense to have that in a separate PR. I can undo that commit. 
(I'm just trying to knock out the backlog of POC related tickets now that are on my plate and picking the easiest ones to start with first)

2023-06-21 00:03 UTC, tiffanychu90 commented
@lauriemerrell: I think the small tweaks here are done, and I went up to generating the docs again. I'm not able to view it in the localhost, but I don't think that's a big deal, and maybe more of a dbt-in-the-Hub issue. 

I took away the 1 month condition too...is that ok? Are there other things for me to do before merging in this PR?

2023-06-21 14:55 UTC, merged