make payments dags run hourly
cal-itp/data-infra pull request #2933
Opened 2023-08-31 15:22 UTC by charlie-costanzo

# Description
The freshness issues we've observed in payments data appear to be correctable with more frequent payments dag runs. This PR changes dag runs to hourly. 

TODO: run transaform_warehouse dag on `--select +fct_payments_rides_v2` hourly at the 45 minute mark ?

## Type of change

- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

2023-08-31 15:26 UTC, lauriemerrell approved these changes

2023-08-31 17:11 UTC, lauriemerrell commented
Ope sorry! I meant to ask -- what changes in bucket structure and/or modeling are needed to account for this? 

See associated work for GTFS:
* https://github.com/cal-itp/data-infra/pull/2460
* https://github.com/cal-itp/data-infra/pull/2510
* https://github.com/cal-itp/data-infra/pull/2511
* https://github.com/cal-itp/data-infra/pull/2531
* https://github.com/cal-itp/data-infra/pull/2561

2023-08-31 17:12 UTC, atvaccaro requested changes
I discussed offline w/ charlie, the parse code needs to change how it queries the files to process in each data interval. I think the artifacts themselves are OK and we don't need a bucket/artifact migration because we timestamp files individually `gs://calitp-payments-littlepay-parsed/micropayment-device-transactions/instance=mendocino-transit-authority/extract_filename=202308290509_micropaymentdevicetransactions.psv/ts=2023-08-30T00:00:38.000731+00:00/202308290509_micropaymentdevicetransactions.jsonl.gz`

2023-09-01 16:11 UTC, atvaccaro commented
@SorenSpicknall can you review?
@charlie-costanzo can you test a couple times, and then monitor after merge to make sure it's working as expected? And then delete the old `parse_littlepay_job_result` files

2023-09-01 16:42 UTC, SorenSpicknall approved these changes
LGTM

2023-09-01 19:18 UTC, merged