Creating an incremental table for vendor vehicle message age by day.
cal-itp/data-infra pull request #3477
Opened 2024-09-25 20:29 UTC by fsalemi

## Creating a new incremental table for vendor vehicle position message age by day.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## How has this been tested?

Yes,
_poetry run dbt run -s +fct_daily_vendor_vehicle_positions_message_age_summary_

`20:17:15  Finished running 12 view models, 11 table models, 1 incremental model in 0 hours 4 minutes and 39.96 seconds (279.96s).
20:17:15  
20:17:15  Completed successfully
20:17:15  
20:17:15  Done. PASS=24 WARN=0 ERROR=0 SKIP=0 TOTAL=24
`

## Post-merge follow-ups

_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and link it here to track resolution._

- [x] No action required
- [ ] Actions required (specified below)

2024-09-25 20:49 UTC, vevetron commented
I'm helping @fsalemi install pre-commit hooks into his environment.

2024-09-26 01:03 UTC, evansiroky requested changes

2024-10-02 00:19 UTC, fsalemi commented
@evansiroky 
Although joining directly with `bridge_organizations_x_gtfs_datasets_produced` also works, but aggregating it would save some processing time since there are a lot of consecutive records for every vendor-to-agency association by date in this table.
I incorporated your requested changes anyways.

2024-10-02 00:33 UTC, fsalemi commented on warehouse/models/mart/gtfs_quality/fct_daily_vendor_vehicle_positions_message_age_summary.sql
> +    AND customer_facing IS TRUE
Thanks or the hint. I deleted customer facing check.

2024-10-02 00:35 UTC, fsalemi commented on warehouse/models/mart/gtfs_quality/fct_daily_vendor_vehicle_positions_message_age_summary.sql
> +),
Thanks for he hint. I used `gtfs_dataset_key` instead.

2024-10-02 18:03 UTC, evansiroky approved these changes
I think this is good for a first pass. I think eventually we may also want to include the trip_id and the organization key. That could be done in a later effort.

Bringing in the organization key would help do more joins to the vendor's record that may be present elsewhere. The trip_id could help analyze things related to whether the vehicle appears to be doing revenue service.

2024-10-02 23:34 UTC, merged