Remove outdated or incorrect users for Hub values.yaml
cal-itp/data-infra pull request #3500
Opened 2024-10-15 17:57 UTC by tiffanychu90

# Description

Changing the `values.yaml` related to JupyterHub so it can spawn up new pods as needed

Resolves #3499

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## How has this been tested?

Don't know how

## Post-merge follow-ups

_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and link it here to track resolution._

- [ ] No action required
- [x] Actions required 

I think there needs to be a deploy to Hub for this to take?

2024-10-15 22:58 UTC, vevetron requested changes

2024-10-16 15:34 UTC, tiffanychu90 commented on kubernetes/apps/charts/jupyterhub/values.yaml
> +      guarantee: 1.0
Ok! Reverting this

2024-10-16 17:56 UTC, vevetron approved these changes

2024-10-16 17:58 UTC, merged

2024-10-16 17:58 UTC, vevetron commented
The description doesn't match the PR but it's probably okay!

This PR is just a little admin cleanup.