NTD: enrich mart tables with caltrans_district, handle ntd_id type
cal-itp/data-infra pull request #3608
Opened 2024-12-19 21:41 UTC by charlie-costanzo

# Description
The PR enriches the newly ingested NTD data tables with caltrans_district to more easily enable analysis by caltrans district in dashboards and elsewhere.

## Type of change
- [x] New feature

## How has this been tested?
<img width="674" alt="Screenshot 2024-12-19 at 4 35 58 PM" src="https://github.com/user-attachments/assets/30945919-e782-4774-bc04-7e15b9ed4b1f" />

## Post-merge follow-ups
- [x] Actions required (specified below)
This enrichment should be further inspected to make sure it's best portraying california agency data

2025-02-04 00:42 UTC, evansiroky requested changes

2025-02-04 16:18 UTC, charlie-costanzo commented on warehouse/models/mart/ntd_annual_reporting/dim_2022_agency_information.sql
> +        dim_organizations.caltrans_district
> I don't think this is appropriate since we usually have used the [bridge_organizations_x_headquarters_county_geography ](https://dbt-docs.calitp.org/#!/model/model.calitp_warehouse.bridge_organizations_x_headquarters_county_geography)and [dim_county_geography](https://dbt-docs.calitp.org/#!/model/model.calitp_warehouse.dim_county_geography) to join to the appropriate Caltrans District. The `Caltrans District` column within Airtable's Organizations table has been deprecated in favor of County Geography which contains Caltrans District.

Hey @evansiroky! Thank you so much for this feedback, this is exactly what I was hoping to validate next when I put up this draft PR.

2025-04-22 16:55 UTC, vevetron commented
@charlie-costanzo can we close this?

2025-04-22 16:59 UTC, charlie-costanzo commented
Closed in favor id 

> @charlie-costanzo can we close this?

ah yes I'm sorry I thought I had closed it... closing this now in favor of #3847

2025-04-22 16:59 UTC, closed without merging