Restructuring and repairing the warehouse tutorial
cal-itp/data-infra pull request #767
Opened 2021-11-20 03:07 UTC by charlie-costanzo

Finally getting around to:

- fixing the markdown issues from the migration
- making it more readable
- making it more accessible to a new user
- incorporating feedback from current analysts

2021-11-22 16:54 UTC, machow requested changes
From pairing with @charlie-costanzo -- thanks, having these as tabbed examples look really nice! Can we try embedding the supplemental explanations that are in tables right now?

For when we have a table explaining what GTFS Schedule Fact Daily Feeds is above the metabase query example, let's move the explanation **into** the example. This will make it a bit easier for people to integrate the information into the example, and help us avoid duplicating a lot of pieces from the example.

![image](https://user-images.githubusercontent.com/2574498/142902208-9b260fb3-8135-46f3-80f2-bf1c2e4595b2.png)

2021-11-23 15:31 UTC, evansiroky commented on docs/analytics_examples/01_warehouse_tutorial.md
> +    count(*) AS count_feeds
This is counting the number of routes, right? Seems like this should be:

```suggestion
    count(*) AS count_routes
```

2021-11-23 15:37 UTC, evansiroky commented on docs/analytics_examples/01_warehouse_tutorial.md
> +### 5. Max Number of Stops a Trip Can Have, Per Agency
Query description suggestion:

```suggestion
### 5. Find the Trip With the Most Number of Stops, Per Agency
```

2021-11-23 15:42 UTC, evansiroky requested changes
See recommended changes, also please fix merge conflict.

2021-11-23 17:34 UTC, charlie-costanzo commented
> See recommended changes, also please fix merge conflict.

Thanks for the review and suggested changed @evansiroky - I committed the changes and fixed the merge conflict.

2021-11-23 18:40 UTC, evansiroky approved these changes

2021-11-23 19:59 UTC, charlie-costanzo commented
@machow now that the changes suggested by Evan are commited, should we merge this to close out existing docs PRs? 

The remaining piece - adding supplemental explanations - is now captured in it's own issue, #779

2021-11-23 22:25 UTC, machow commented
@charlie-costanzo sounds good--thanks for the changes / catching the rest in an issue

2021-11-23 22:25 UTC, merged